name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v3

      - name: Delete files
        run: sshpass -p ${{ secrets.HOST_USER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ vars.HOST_USER_NAME }}@${{ vars.HOST }} "cd ${{ vars.DEPLOY_PATH }} && ls ${{ vars.DEPLOY_PATH }}/* | egrep -v storage | xargs rm -rf "

      - name: Upload files
        run: sshpass -p ${{ secrets.HOST_USER_PASSWORD }} scp -r -o StrictHostKeyChecking=no ./target/springboot-demo.jar ${{ vars.HOST_USER_NAME }}@${{ vars.HOST }}:${{ vars.DEPLOY_PATH }}

      # java 执行路径也可以根据自己需要更改下，我这里指定了 /www/server/java/jdk-17.0.8/bin/java
      - name: Run
        run: sshpass -p ${{ secrets.HOST_USER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ vars.HOST_USER_NAME }}@${{ vars.HOST }} "cd ${{ vars.DEPLOY_PATH }} && /www/server/java/jdk-17.0.8/bin/java -jar springboot-demo.jar"